"""add name column to clubs table

Revision ID: e991177c60f6
Revises: d66e8ef134dd
Create Date: 2025-01-14 23:09:56.329990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e991177c60f6'
down_revision = 'd66e8ef134dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('name', sa.String(length=255), nullable=False, server_default="Untitled Club")
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
